apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openbao.fullname" . }}-config
  labels:
    app: {{ include "openbao.fullname" . }}
data:
  config.hcl: |
    {{ .Values.openbao.config.hcl | nindent 4 }}