apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbao.fullname" . }}-postgresql
  labels:
    app: {{ include "openbao.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "openbao.fullname" . }}-postgresql
  template:
    metadata:
      labels:
        app: {{ include "openbao.fullname" . }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "openbao.fullname" . }}-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "openbao.fullname" . }}-secrets
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "openbao.fullname" . }}-secrets
                  key: database
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: {{ include "openbao.fullname" . }}-postgresql-pvc