apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbao.fullname" . }}-postgresql
  labels:
    app: {{ include "openbao.fullname" . }}
spec:
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
  selector:
    app: {{ include "openbao.fullname" . }}-postgresql