apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openbao.fullname" . }}-secrets
  labels:
    app: {{ include "openbao.fullname" . }}
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
  database: {{ .Values.postgresql.database | b64enc | quote }}